# Generated by Django 3.1.7 on 2021-07-13 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coscudo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regist',
            name='email',
        ),
        migrations.RemoveField(
            model_name='regist',
            name='name',
        ),
        migrations.RemoveField(
            model_name='regist',
            name='phone',
        ),
    ]
